events {}

http {
    server {
        listen 80;
        absolute_redirect off;

        location /app/ai-thread {
            proxy_pass http://ai-thread:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /app/dashboard {
            proxy_pass http://dashboard:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        
        location /app/me {
            proxy_pass http://me:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location = / {
            return 301 /app/me;
        }
    }
}
